// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.ibericsoft.scm.persistence.domain;

import org.ibericsoft.scm.persistence.domain.Content;

privileged aspect Content_Roo_JavaBean {
    
    public String Content.getContent() {
        return this.content;
    }
    
    public void Content.setContent(String content) {
        this.content = content;
    }
    
}
